import { lessonSchema } from "./lesson";

const words = [
  [
    "bunch",
    2,
    5,
    "The ending is nch. The ch letters work together to make one sound.",
    "A group of things together.",
  ],
  [
    "fruit",
    2,
    4,
    "The long oo sound is spelled ui.",
    "A sweet food that grows on a plant.",
  ],
  [
    "argue",
    2,
    5,
    "The ending is gue: g, u, then a silent e.",
    "To disagree with someone.",
  ],
  [
    "crumb",
    3,
    5,
    "It ends in mb. The b is silent.",
    "A tiny piece of bread or cake.",
  ],
  [
    "crew",
    2,
    4,
    "The oo sound at the end is spelled ew.",
    "A group working together.",
  ],
  [
    "tune",
    1,
    4,
    "The ending is une. The silent e helps the u say its name.",
    "A melody you can sing.",
  ],
  [
    "juice",
    1,
    5,
    "Write ui for the oo sound, then ce for the soft s sound.",
    "A drink made from squeezed fruit.",
  ],
  [
    "refuse",
    2,
    6,
    "After re, write fuse. The s sounds like z, and the final e is silent.",
    "To say you will not do something.",
  ],
  [
    "truth",
    3,
    5,
    "The final sound is made by the two letters th.",
    "Something that is real or correct.",
  ],
  [
    "young",
    1,
    5,
    "After y, write ou for the short u sound, then ng.",
    "Not very old.",
  ],
  [
    "clue",
    1,
    4,
    "After c, write lue. The l joins c in the cl blend; ue makes the oo sound.",
    "Something that helps solve a mystery.",
  ],
  [
    "trunk",
    3,
    5,
    "The ending sound uses nk, with n before k.",
    "A large box for storing things.",
  ],
  [
    "amuse",
    1,
    5,
    "After a, write muse. The s sounds like z, and the final e is silent.",
    "To make someone smile or laugh.",
  ],
  ["suit", 1, 3, "The oo sound is spelled ui.", "A matching set of clothes."],
  [
    "rude",
    1,
    4,
    "Write ude after r. Remember the silent final e.",
    "Unkind or impolite.",
  ],
  [
    "trust",
    3,
    5,
    "The word ends with the consonant blend st.",
    "To believe someone will do the right thing.",
  ],
  [
    "dew",
    1,
    3,
    "The long oo sound at the end is spelled ew.",
    "Tiny drops of water on grass in the morning.",
  ],
  [
    "stuck",
    3,
    5,
    "After the short vowel, the k sound is spelled ck.",
    "Unable to move or get free.",
  ],
  [
    "rescue",
    3,
    6,
    "The ending is cue: c, u, then a silent e.",
    "To help someone get out of danger.",
  ],
  [
    "brush",
    3,
    5,
    "The final sound is spelled with two letters: sh.",
    "A tool with bristles for tidying hair.",
  ],
  [
    "computer",
    3,
    7,
    "Between com and r, write pute: p, u, t, e.",
    "An electronic machine used to work, play, and find information.",
  ],
  [
    "mustard",
    4,
    7,
    "The last syllable is spelled ard, even if it sounds like erd.",
    "A yellow sauce often put on sandwiches.",
  ],
  [
    "tissue",
    2,
    6,
    "After ti, write two s letters, then ue.",
    "A soft piece of paper for wiping or cleaning.",
  ],
  [
    "customer",
    3,
    7,
    "Between cus and r, write tome. The o has a soft, unstressed sound.",
    "Someone buying something from a shop.",
  ],
  [
    "attitude",
    1,
    3,
    "After the a, write two t letters. Don't forget the double tt.",
    "The way someone thinks or feels about something.",
  ],
] as const;
const t = (text: string) => ({ text });
const w = (wordId: string) => ({ wordId });

export const featuredLesson = lessonSchema.parse({
  schemaVersion: 1,
  title: "The Secret Sparkle Parade",
  grade: 4,
  theme: { name: "Sparkle garden club", emoji: "🦋", accent: "violet" },
  words: words.map(([spelling, start, end, hint, definition]) => ({
    id: spelling,
    spelling,
    trickySpans: [{ start, end }],
    hint,
    definition,
  })),
  chapters: [
    {
      title: "The invitation",
      tokens: [
        t("Mia tied a "),
        w("bunch"),
        t(
          " of pink ribbons to her bicycle basket. Today was the secret garden parade! She packed ",
        ),
        w("fruit"),
        t(" for her friends, who could never "),
        w("argue"),
        t(" for long when snacks were nearby. A glittery "),
        w("crumb"),
        t(" on the path caught her eye. “That’s odd,” she said. Her parade "),
        w("crew"),
        t(" gathered around to investigate."),
      ],
    },
    {
      title: "A very tiny voice",
      tokens: [
        t("From behind a rosebush came a wobbly "),
        w("tune"),
        t(". Mia set down her peach "),
        w("juice"),
        t(" and listened. “We can’t "),
        w("refuse"),
        t(" to help,” she whispered. “The "),
        w("truth"),
        t(" is, someone sounds lost.” A "),
        w("young"),
        t(
          " kitten wearing a lilac bow peeked out from the leaves. Her name tag said Princess Pickles.",
        ),
      ],
    },
    {
      title: "Princess Pickles has a plan",
      tokens: [
        t("The kitten dropped a shiny "),
        w("clue"),
        t(" at Mia’s feet: a tiny silver key. It opened an old "),
        w("trunk"),
        t(" beside the fountain. Inside were costumes meant to "),
        w("amuse"),
        t(" the parade guests, including a butterfly "),
        w("suit"),
        t(" with enormous wings. “Taking all these without asking would be "),
        w("rude"),
        t(
          ",” said Mia. A note inside read: Please dress up! Love, the Garden Club.",
        ),
      ],
    },
    {
      title: "A little kitten magic",
      tokens: [
        t("“You can "),
        w("trust"),
        t(
          " us, Pickles,” Mia said. They followed paw prints through the morning ",
        ),
        w("dew"),
        t(". By the gate, a smaller kitten was "),
        w("stuck"),
        t(
          " under a fallen flower basket! Together, the friends made a gentle ",
        ),
        w("rescue"),
        t(". Mia used a soft "),
        w("brush"),
        t(
          " to tidy the kitten’s fluffy fur. Princess Pickles purred so loudly that everyone giggled.",
        ),
      ],
    },
    {
      title: "The brightest parade",
      tokens: [
        t("Back at the garden shop, the owner checked her "),
        w("computer"),
        t(
          ". The kittens belonged to her! She thanked the girls with sandwiches, though Mia skipped the ",
        ),
        w("mustard"),
        t(". A kind friend passed her a "),
        w("tissue"),
        t(" to wipe a pink frosting dot from her nose. Every "),
        w("customer"),
        t(" cheered as the parade began. With her cheerful "),
        w("attitude"),
        t(
          " and giant butterfly wings, Mia led the way. Even the kittens wore tiny crowns.",
        ),
      ],
    },
  ],
});
